#!/bin/bash
# cx <node> <swarm-service> <cmd...> -- exec in the (first) task container of a service on a test node
B=$(dirname "$0")
n=$1
svc=$2
shift 2
"$B/s" "$n" "c=\$(docker ps -q -f label=com.docker.swarm.service.name=$svc | head -1); docker exec \$c sh -c '$*'"
