#!/bin/bash
# cxs <node> <service> <script> [args...] -- run a local script in the service's task container on a node
B=$(dirname "$0")
n=$1
svc=$2
f=$3
shift 3
"$B/s" "$n" "c=\$(docker ps -q -f label=com.docker.swarm.service.name=$svc | head -1); docker exec -i \$c sh -s -- $*" <"$f"
